"""
solid-name: TestCodexPrincipleReview
solid-category: integration-test
solid-description: Integration tests for all principles using the Codex backend.
Runs apply and health flows against all fixture-backed principles.
Expectation mismatches are acceptable at this stage — only infrastructure
failures cause test failure.

Run:
    python3 -m pytest tests/harness/integration_tests/test_codex.py -v
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from integration_tests.base import IntegrationTestBase  # noqa: E402

_PROJECT_ROOT = Path(__file__).resolve().parents[3]
_CODEX_PROJECT_CONFIG = _PROJECT_ROOT / ".codex" / "config.toml"
_MARKETPLACE_NAME = "solid-coder-dev-local"
_PLUGIN_NAME = "solid-coder"

_LOCAL_MARKETPLACE_CONFIG = f"""\
# auto-generated by test_codex.py — registers this checkout as a local codex
# plugin marketplace so live codex sessions use the dev repo under test
# instead of whatever version is globally installed. Removed in tearDownClass.

[features]
plugins = true

[marketplaces.{_MARKETPLACE_NAME}]
source_type = "local"
source = "{_PROJECT_ROOT}"

[plugins."{_PLUGIN_NAME}@{_MARKETPLACE_NAME}"]
enabled = true
"""


class TestCodexPrincipleReview(IntegrationTestBase):
    """Principle review integration tests using the Codex backend.

    Uses the codex.toml model profile which routes to the Codex LLM backend.
    Timeout matches the profile's configured limit.
    """

    __test__ = True
    MODEL_PROFILE = "codex"
    TIMEOUT = 300

    @classmethod
    def setUpClass(cls) -> None:
        super().setUpClass()
        _CODEX_PROJECT_CONFIG.parent.mkdir(parents=True, exist_ok=True)
        _CODEX_PROJECT_CONFIG.write_text(_LOCAL_MARKETPLACE_CONFIG, encoding="utf-8")

    @classmethod
    def tearDownClass(cls) -> None:
        _CODEX_PROJECT_CONFIG.unlink(missing_ok=True)
        super().tearDownClass()
