#!/usr/bin/env python3
"""Compute token cost per principle × per pipeline mode.

Invokes the gateway to discover principles and measure what each pipeline mode
actually loads. Emits a markdown table with:
  - per-principle × per-mode tokens
  - per-mode totals: MIN (always-on principles only) and MAX (all principles)

Usage:
    python3 scripts/token-cost-by-mode.py
    python3 scripts/token-cost-by-mode.py --out .claude/docs/token-cost-by-mode.md
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
GATEWAY = PROJECT_ROOT / "mcp-server" / "gateway.py"


# Mode → gateway flags (mirrors what each skill passes to load-reference)
MODES = {
    "code":        ["--profile", "code", "--exclude", "instructions,examples"],
    "review":      ["--profile", "review"],
    "planner":     ["--profile", "code", "--exclude", "examples,patterns"],
    "synth-impl":  ["--profile", "code", "--exclude", "examples,instructions"],
    "synth-fixes": ["--profile", "code", "--exclude", "examples"],
}

# Aggregation per mode:
#   "all"           — loads every active principle into the same context (cost = sum)
#   "per-principle" — each subagent/invocation loads ONE principle in isolation (cost = single principle)
MODE_AGGREGATION = {
    "code":        "all",
    "review":      "per-principle",  # apply-principle-review runs one subagent per principle
    "planner":     "all",
    "synth-impl":  "all",
    "synth-fixes": "all",             # loads in a loop but all land in the same context
}

# Mode → user-facing skill label
MODE_LABELS = {
    "code":        "`code` (`/code`, `/implement` coding phase)",
    "review":      "`review` (`apply-principle-review`)",
    "planner":     "`planner` (`plan`)",
    "synth-impl":  "`synth-impl` (`synthesize-implementation`)",
    "synth-fixes": "`synth-fixes` (`synthesize-fixes`)",
}

# Mode → what it loads from a principle folder (for the profile table)
MODE_LOADS = {
    #              rule  code   fix   review examples patterns
    "code":        (True, True, False, False, False, True),
    "review":      (True, False, False, True, True, True),
    "planner":     (True, True, True, False, False, False),
    "synth-impl":  (True, True, False, False, False, True),
    "synth-fixes": (True, True, True, False, False, True),
}
LOAD_COLUMNS = ["rule.md", "code/instructions.md", "fix/instructions.md",
                "review/instructions.md", "Examples", "required_patterns"]

CHARS_PER_TOKEN = 4


def run(*args):
    r = subprocess.run(["python3", str(GATEWAY), *args],
                       capture_output=True, text=True, cwd=PROJECT_ROOT)
    return r.stdout, r.returncode, r.stderr


def discover_principles():
    out, rc, err = run("discover_principles")
    if rc != 0:
        print(f"Error: discover_principles failed: {err}", file=sys.stderr)
        sys.exit(1)
    data = json.loads(out)
    return data["active_principles"]


def tokens_for(mode_args, principle):
    out, rc, _ = run("load_rules", *mode_args, "--principle", principle)
    if rc != 0:
        return None
    return len(out) // CHARS_PER_TOKEN


def measure():
    principles = discover_principles()
    table = {}  # (mode, principle) → tokens
    always_on = []
    conditional = []
    for p in principles:
        name = p["name"]
        if p.get("tags"):
            conditional.append(name)
        else:
            always_on.append(name)
        for mode, args in MODES.items():
            table[(mode, name)] = tokens_for(args, name)
    return principles, always_on, conditional, table


def render(principles, always_on, conditional, table) -> str:
    lines = []
    lines.append("# Token Cost per Principle (by loading mode)")
    lines.append("")
    lines.append("Auto-generated by `scripts/token-cost-by-mode.py`. Regenerate when principle docs change:")
    lines.append("")
    lines.append("```bash")
    lines.append("python3 scripts/token-cost-by-mode.py --out .claude/docs/token-cost-by-mode.md")
    lines.append("```")
    lines.append("")
    lines.append(f"Tokens ≈ chars / {CHARS_PER_TOKEN}, measured by invoking `gateway.py load_rules` per principle per mode. YAML frontmatter is stripped.")
    lines.append("")
    lines.append("## Per-principle × mode")
    lines.append("")

    header = ["Principle", "Activation"] + list(MODES.keys())
    lines.append("| " + " | ".join(header) + " |")
    lines.append("|" + "|".join(["---"] + ["---"] + ["---:"] * len(MODES)) + "|")

    # Sort: always-on first (alphabetical), then conditional (alphabetical)
    ordered = sorted(always_on) + sorted(conditional)
    display_names = {p["name"]: p.get("displayName") or p["name"] for p in principles}

    for name in ordered:
        activation = "always" if name in always_on else "conditional"
        row = [display_names.get(name, name), activation]
        for mode in MODES:
            v = table.get((mode, name))
            row.append(f"{v:,}" if v is not None else "—")
        lines.append("| " + " | ".join(row) + " |")

    # MIN row — smallest realistic load per mode
    min_row = ["**MIN**", ""]
    min_notes = []
    for mode in MODES:
        if MODE_AGGREGATION[mode] == "all":
            total = sum(table[(mode, n)] or 0 for n in always_on)
            min_row.append(f"**{total:,}**")
        else:
            vals = [table[(mode, n)] for n in ordered if table[(mode, n)] is not None]
            total = min(vals) if vals else 0
            min_row.append(f"**{total:,}**")
    lines.append("| " + " | ".join(min_row) + " |")

    # MAX row — heaviest realistic load per mode
    max_row = ["**MAX**", ""]
    for mode in MODES:
        if MODE_AGGREGATION[mode] == "all":
            total = sum(table[(mode, n)] or 0 for n in ordered)
            max_row.append(f"**{total:,}**")
        else:
            vals = [table[(mode, n)] for n in ordered if table[(mode, n)] is not None]
            total = max(vals) if vals else 0
            max_row.append(f"**{total:,}**")
    lines.append("| " + " | ".join(max_row) + " |")

    lines.append("")
    lines.append("**Aggregation per mode**:")
    for mode, agg in MODE_AGGREGATION.items():
        if agg == "all":
            lines.append(f"- `{mode}` — loads **all** active principles in one context. MIN = {len(always_on)} always-on principles summed. MAX = all {len(ordered)} principles summed.")
        else:
            lines.append(f"- `{mode}` — each subagent loads **one** principle in isolation. MIN = smallest single-principle cost. MAX = largest single-principle cost.")
    lines.append("")

    # Mode load profiles
    lines.append("## Mode load profiles")
    lines.append("")
    lines.append("What each mode includes from a principle folder. Source: `mcp-server/server.py::load_rules`.")
    lines.append("")
    header = ["Mode"] + LOAD_COLUMNS
    lines.append("| " + " | ".join(header) + " |")
    lines.append("|" + "|".join(["---"] + [":-:"] * len(LOAD_COLUMNS)) + "|")
    for mode, label in MODE_LABELS.items():
        row = [label]
        for incl in MODE_LOADS[mode]:
            row.append("✅" if incl else "—")
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")
    lines.append("See [token-budget.md](token-budget.md) for a per-file / per-folder breakdown (independent of mode).")

    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--out", default=None, help="Write markdown doc to this path (default: stdout)")
    args = ap.parse_args()

    principles, always_on, conditional, table = measure()
    md = render(principles, always_on, conditional, table)

    if args.out:
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(md, encoding="utf-8")
        print(f"Wrote {out_path}", file=sys.stderr)
    else:
        print(md)


if __name__ == "__main__":
    main()
