#!/usr/bin/env python3
"""Compute a hierarchical token-budget breakdown of a references tree.

Walks a directory, estimates tokens per file (chars // 4), and aggregates
totals up the folder hierarchy. Emits a markdown report to stdout.

Usage:
    python3 scripts/token-budget.py [--root references/principles] [--out docs/token-budget.md]

When --out is given, writes the full markdown document (with header + table).
Without --out, prints the table fragment only.
"""

import argparse
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional


CHARS_PER_TOKEN = 4  # rough heuristic; Anthropic tokenizer is similar


@dataclass
class Node:
    path: Path
    name: str
    is_file: bool
    tokens: int = 0
    chars: int = 0
    children: List["Node"] = field(default_factory=list)

    @property
    def sort_key(self):
        # folders first, then files; alphabetical within group
        return (self.is_file, self.name.lower())


def strip_frontmatter(text: str) -> str:
    """Mirror load-reference behavior: strip leading YAML frontmatter."""
    if not text.startswith("---"):
        return text
    end = text.find("---", 3)
    if end == -1:
        return text
    body_start = end + 3
    if body_start < len(text) and text[body_start] == "\n":
        body_start += 1
    return text[body_start:]


def should_skip(path: Path) -> bool:
    name = path.name
    if name.startswith("."):
        return True
    if name in {"__pycache__", "node_modules"}:
        return True
    return False


def build_tree(root: Path, include_exts: Optional[set] = None) -> Node:
    node = Node(path=root, name=root.name, is_file=root.is_file())
    if root.is_file():
        if include_exts and root.suffix.lower() not in include_exts:
            return node
        try:
            text = root.read_text(encoding="utf-8", errors="replace")
        except Exception:
            return node
        body = strip_frontmatter(text)
        node.chars = len(body)
        node.tokens = node.chars // CHARS_PER_TOKEN
        return node

    for child in sorted(root.iterdir(), key=lambda p: (p.is_file(), p.name.lower())):
        if should_skip(child):
            continue
        c = build_tree(child, include_exts=include_exts)
        node.children.append(c)
        node.tokens += c.tokens
        node.chars += c.chars
    return node


def render_rows(node: Node, depth: int, rows: list, root_depth: int = 0):
    indent = "&nbsp;&nbsp;&nbsp;&nbsp;" * max(0, depth - root_depth)
    icon = "📄" if node.is_file else "📁"
    label = f"{indent}{icon} `{node.name}`"
    rows.append((label, node.tokens, node.chars))
    if not node.is_file:
        for child in sorted(node.children, key=lambda n: n.sort_key):
            render_rows(child, depth + 1, rows, root_depth=root_depth)


def render_markdown(node: Node, title: str = None) -> str:
    lines = []
    if title:
        lines.append(f"## {title}\n")
    lines.append(f"**Root**: `{node.path}`  ")
    lines.append(f"**Total**: {node.tokens:,} tokens ({node.chars:,} chars)\n")

    lines.append("| Path | Tokens | Chars |")
    lines.append("|---|---:|---:|")
    rows: list = []
    render_rows(node, depth=0, rows=rows, root_depth=0)
    for label, tokens, chars in rows:
        lines.append(f"| {label} | {tokens:,} | {chars:,} |")
    return "\n".join(lines)


def render_doc(node: Node) -> str:
    header = [
        "# Token Budget — references/",
        "",
        f"Hierarchical token estimate for `{node.path}`. Tokens ≈ chars / {CHARS_PER_TOKEN}.",
        "Generated by `scripts/token-budget.py`. Re-run after changing principle docs:",
        "",
        "```bash",
        "python3 scripts/token-budget.py --out .claude/docs/token-budget.md",
        "```",
        "",
        "YAML frontmatter is stripped before counting (matches `load-reference` behavior).",
        "Folder totals are the sum of their children.",
        "",
    ]
    return "\n".join(header) + "\n" + render_markdown(node) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument(
        "--root",
        default="references/principles",
        help="Root folder to walk (default: references/principles)",
    )
    ap.add_argument(
        "--out",
        default=None,
        help="Write full markdown doc to this path. Otherwise prints table to stdout.",
    )
    ap.add_argument(
        "--ext",
        action="append",
        default=None,
        help="Include only these extensions (repeatable). Default: all files.",
    )
    args = ap.parse_args()

    root = Path(args.root).resolve()
    if not root.exists():
        print(f"Error: root not found: {root}", file=sys.stderr)
        sys.exit(1)

    include_exts = set(e if e.startswith(".") else f".{e}" for e in args.ext) if args.ext else None
    tree = build_tree(root, include_exts=include_exts)

    if args.out:
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(render_doc(tree), encoding="utf-8")
        print(f"Wrote {out_path} ({tree.tokens:,} tokens total)", file=sys.stderr)
    else:
        print(render_markdown(tree))


if __name__ == "__main__":
    main()
