#!/usr/bin/env python3
"""Compute token cost per principle × per pipeline mode.

Modes, their load configuration, and aggregation strategy live in
`mcp-server/modes.py` — the single source of truth. This script imports from
there so principle docs stay in sync with what skills actually load.

Usage:
    python3 scripts/token-cost-by-mode.py
    python3 scripts/token-cost-by-mode.py --out .claude/docs/token-cost-by-mode.md
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
GATEWAY = PROJECT_ROOT / "mcp-server" / "gateway.py"

# Import the centralized mode config
sys.path.insert(0, str(PROJECT_ROOT / "mcp-server"))
import modes as modes_module  # noqa: E402

MODES = modes_module.MODES
SECTION_LABELS = modes_module.SECTION_LABELS

CHARS_PER_TOKEN = 4


def run(*args):
    r = subprocess.run(["python3", str(GATEWAY), *args],
                       capture_output=True, text=True, cwd=PROJECT_ROOT)
    return r.stdout, r.returncode, r.stderr


def discover_principles():
    out, rc, err = run("discover_principles")
    if rc != 0:
        print(f"Error: discover_principles failed: {err}", file=sys.stderr)
        sys.exit(1)
    data = json.loads(out)
    return data["active_principles"]


def tokens_for(mode, principle):
    out, rc, _ = run("load_rules", "--mode", mode, "--principle", principle)
    if rc != 0:
        return None
    return len(out) // CHARS_PER_TOKEN


def measure():
    principles = discover_principles()
    table = {}
    always_on = []
    conditional = []
    for p in principles:
        name = p["name"]
        (conditional if p.get("tags") else always_on).append(name)
        for mode in MODES:
            table[(mode, name)] = tokens_for(mode, name)
    return principles, always_on, conditional, table


def render_loads_column(mode: str) -> str:
    loads = MODES[mode]["loads"]
    return ", ".join(SECTION_LABELS[s] for s in loads)


def render(principles, always_on, conditional, table) -> str:
    lines = []
    lines.append("# Token Cost per Principle (by loading mode)")
    lines.append("")
    lines.append("Auto-generated by `scripts/token-cost-by-mode.py`. Regenerate when principle docs change:")
    lines.append("")
    lines.append("```bash")
    lines.append("python3 scripts/token-cost-by-mode.py --out .claude/docs/token-cost-by-mode.md")
    lines.append("```")
    lines.append("")
    lines.append(f"Tokens ≈ chars / {CHARS_PER_TOKEN}, measured by invoking `gateway.py load_rules --mode <mode>` per principle per mode. YAML frontmatter is stripped. Mode definitions live in `mcp-server/modes.py`.")
    lines.append("")

    # Per-mode: what it loads
    lines.append("## What each mode loads")
    lines.append("")
    lines.append("| Mode | Loads (from each principle folder) | Aggregation |")
    lines.append("|---|---|---|")
    for mode, cfg in MODES.items():
        agg = "all principles → one context" if cfg["aggregation"] == "all" else "one principle per subagent"
        lines.append(f"| `{mode}` | {render_loads_column(mode)} | {agg} |")
    lines.append("")
    lines.append("Skills pass `--mode <name>` to `gateway.py load_rules`; the server resolves profile + exclude from `mcp-server/modes.py`. Skills do not specify exclude lists directly.")
    lines.append("")

    # Per-principle × mode
    lines.append("## Per-principle × mode (tokens)")
    lines.append("")

    header = ["Principle", "Activation"] + list(MODES.keys())
    lines.append("| " + " | ".join(header) + " |")
    lines.append("|" + "|".join(["---"] + ["---"] + ["---:"] * len(MODES)) + "|")

    ordered = sorted(always_on) + sorted(conditional)
    display_names = {p["name"]: p.get("displayName") or p["name"] for p in principles}

    for name in ordered:
        activation = "always" if name in always_on else "conditional"
        row = [display_names.get(name, name), activation]
        for mode in MODES:
            v = table.get((mode, name))
            row.append(f"{v:,}" if v is not None else "—")
        lines.append("| " + " | ".join(row) + " |")

    # MIN row
    min_row = ["**MIN**", ""]
    for mode in MODES:
        if MODES[mode]["aggregation"] == "all":
            total = sum(table[(mode, n)] or 0 for n in always_on)
        else:
            vals = [table[(mode, n)] for n in ordered if table[(mode, n)] is not None]
            total = min(vals) if vals else 0
        min_row.append(f"**{total:,}**")
    lines.append("| " + " | ".join(min_row) + " |")

    # MAX row
    max_row = ["**MAX**", ""]
    for mode in MODES:
        if MODES[mode]["aggregation"] == "all":
            total = sum(table[(mode, n)] or 0 for n in ordered)
        else:
            vals = [table[(mode, n)] for n in ordered if table[(mode, n)] is not None]
            total = max(vals) if vals else 0
        max_row.append(f"**{total:,}**")
    lines.append("| " + " | ".join(max_row) + " |")

    lines.append("")
    lines.append(f"- **MIN** = smallest realistic load for that mode. For `all` aggregation: sum of always-on principles ({len(always_on)}). For `per-principle`: smallest single principle.")
    lines.append(f"- **MAX** = heaviest realistic load. For `all`: sum of all discovered principles ({len(ordered)}). For `per-principle`: largest single principle.")
    lines.append("")

    lines.append("See [token-budget.md](token-budget.md) for a per-file / per-folder breakdown (independent of mode).")

    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--out", default=None, help="Write markdown doc to this path (default: stdout)")
    args = ap.parse_args()

    principles, always_on, conditional, table = measure()
    md = render(principles, always_on, conditional, table)

    if args.out:
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(md, encoding="utf-8")
        print(f"Wrote {out_path}", file=sys.stderr)
    else:
        print(md)


if __name__ == "__main__":
    main()
