"""
solid-name: test_flow_session_scoping_live
solid-category: integration-test
solid-spec: [SPEC-013]
solid-description: Verifies against real Claude and Codex sessions that the active-run
pointer file actually gets session-scoped (active-{session_id}.json) rather than silently
falling back to the unscoped active.json — proving McpRequestContextSessionReader's
env-var (Claude) and call-meta (Codex) assumptions hold against real sessions, not just
the stubs used in the unit tests.

Not part of the fast unit-test sweep — spawns real LLM sessions. Run explicitly:
    python3 -m pytest tests/harness/flow_engine/test_flow_session_scoping_live.py -v
"""

from __future__ import annotations

import subprocess
import sys
import unittest
from pathlib import Path

_MCP_SERVER = Path(__file__).resolve().parents[3] / "mcp-server"
_MCP_HEALTH = _MCP_SERVER / "health"
_MCP_HEALTH_CONFIG = _MCP_HEALTH / "config"
_MCP_HEALTH_CODEX = _MCP_HEALTH / "codex"
for _d in (_MCP_SERVER, _MCP_HEALTH_CONFIG, _MCP_HEALTH_CODEX):
    if str(_d) not in sys.path:
        sys.path.insert(0, str(_d))

from hc_codex_runner import make_codex_runner  # noqa: E402
from hook_utils import solid_coder_project_dir  # noqa: E402
from mcp_config_builder import build_mcp_config  # noqa: E402

_PROJECT_ROOT = _MCP_SERVER.parent
_ALLOWED_TOOLS = "mcp__pipeline__flow_start,mcp__solid-coder-pipeline__flow_start"
_SMOKE_PROMPT = 'Call the mcp__pipeline__flow_start tool with flow="e2e_test". Do not call any other tool.'
# FlowFileResolver falls back to the raw `flow` value unchanged when search-path lookup
# misses, so an absolute path sidesteps any {project} / cwd mismatch between how Claude
# and Codex resolve the MCP server subprocess's working directory.
_E2E_FLOW_ABS_PATH = str(_PROJECT_ROOT / ".solid-coder" / "harness" / "flows" / "e2e_test.yaml")
_CODEX_SMOKE_PROMPT = (
    f'Call the mcp__pipeline__flow_start tool exactly once, with flow="{_E2E_FLOW_ABS_PATH}". '
    "IMPORTANT: after that single call returns, immediately reply with the word DONE and stop. "
    "Do NOT call mcp__pipeline__flow_next or any other tool afterward, even if the result "
    "suggests further steps are ready — this is a test of flow_start alone."
)

_CODEX_PROJECT_CONFIG = _PROJECT_ROOT / ".codex" / "config.toml"
_MARKETPLACE_NAME = "solid-coder-dev-local"
_PLUGIN_NAME = "solid-coder"

# Registers this checkout as a local codex plugin marketplace so the spawned codex
# session uses the dev repo under test instead of whatever stale version is globally
# installed at ~/.codex/plugins/cache/ — without this, a stale global plugin's own
# pre_write_gate.py fires independently and can hang/confuse the model. See
# handover-flow-hooks-and-timeout-consolidation.md section 2. Mirrors test_codex.py.
_LOCAL_MARKETPLACE_CONFIG = f"""\
# auto-generated by test_flow_session_scoping_live.py — removed in tearDownClass.

[features]
plugins = true

[marketplaces.{_MARKETPLACE_NAME}]
source_type = "local"
source = "{_PROJECT_ROOT}"

[plugins."{_PLUGIN_NAME}@{_MARKETPLACE_NAME}"]
enabled = true
"""


def _runs_dir() -> Path:
    return solid_coder_project_dir(_PROJECT_ROOT) / "runs"


def _active_pointer_files() -> set:
    runs = _runs_dir()
    if not runs.exists():
        return set()
    return set(runs.glob("active*.json"))


def _clear_active_pointers() -> None:
    for pointer in _active_pointer_files():
        pointer.unlink(missing_ok=True)


class TestFlowSessionScopingLiveClaude(unittest.TestCase):
    """Live smoke test: does a real Claude session's active-run pointer get session-scoped?"""

    TIMEOUT = 180

    def setUp(self):
        _clear_active_pointers()

    def tearDown(self):
        _clear_active_pointers()

    def test_claude_session_produces_a_session_scoped_pointer_file(self):
        before = _active_pointer_files()

        subprocess.run(
            [
                "claude", "-p", _SMOKE_PROMPT, "--output-format", "json",
                "--mcp-config", build_mcp_config(_PROJECT_ROOT),
                "--allowedTools", _ALLOWED_TOOLS,
                "--plugin-dir", str(_PROJECT_ROOT),
            ],
            capture_output=True, text=True, timeout=self.TIMEOUT,
            cwd=str(_PROJECT_ROOT), stdin=subprocess.DEVNULL,
        )

        after = _active_pointer_files()
        new_files = after - before
        self.assertTrue(new_files, "No active-run pointer file appeared after the Claude session")
        pointer = new_files.pop()
        self.assertNotEqual(
            pointer.name, "active.json",
            "Pointer file is the unscoped active.json — CLAUDE_CODE_SESSION_ID did not resolve "
            "inside the MCP server subprocess; session-scoping silently fell back to the old behavior."
        )


class TestFlowSessionScopingLiveCodex(unittest.TestCase):
    """Live smoke test: does a real Codex session's active-run pointer get session-scoped?"""

    TIMEOUT = 180

    @classmethod
    def setUpClass(cls) -> None:
        _CODEX_PROJECT_CONFIG.parent.mkdir(parents=True, exist_ok=True)
        _CODEX_PROJECT_CONFIG.write_text(_LOCAL_MARKETPLACE_CONFIG, encoding="utf-8")

    @classmethod
    def tearDownClass(cls) -> None:
        _CODEX_PROJECT_CONFIG.unlink(missing_ok=True)

    def setUp(self):
        _clear_active_pointers()

    def tearDown(self):
        _clear_active_pointers()

    def test_codex_session_produces_a_session_scoped_pointer_file(self):
        before = _active_pointer_files()

        result = make_codex_runner(cwd=str(_PROJECT_ROOT)).run(prompt=_CODEX_SMOKE_PROMPT, timeout=self.TIMEOUT)
        print(f"\n--- codex last message ---\n{result}\n--- end ---\n", flush=True)

        after = _active_pointer_files()
        new_files = after - before
        self.assertTrue(new_files, f"No active-run pointer file appeared after the Codex session. Last message: {result}")
        pointer = new_files.pop()
        self.assertNotEqual(
            pointer.name, "active.json",
            "Pointer file is the unscoped active.json — Codex's _meta.threadId / "
            "x-codex-turn-metadata.session_id did not resolve; session-scoping silently "
            "fell back to the old behavior."
        )


if __name__ == "__main__":
    unittest.main()
